namespace SwiftList.PluginSdk;

/// <summary>
/// Represents a provider that generates dynamic action items at runtime
/// (e.g. the dynamic Windows Shell Context Menu).
/// </summary>
public interface IDynamicActionProvider
{
    /// <summary>The group name this dynamic action provider belongs to (e.g., "Shortcut Menu").</summary>
    string GroupName { get; }

    /// <summary>Keywords that expose this provider as a search result instead of an action-menu provider.</summary>
    IReadOnlyList<string> Keywords => Array.Empty<string>();

    /// <summary>Parameter names used for displaying the search-result form of this provider.</summary>
    IReadOnlyList<string> Parameters => Array.Empty<string>();

    /// <summary>Determines whether this provider is visible in the search result matching for the given window type.</summary>
    bool IsVisibleInSearch(ISearchResult result, SearchWindowType windowType) => true;

    /// <summary>Determines whether this provider should be visible in the right-click / action menu.</summary>
    bool IsVisibleInMenu(ISearchResult result, SearchWindowType windowType) => Keywords.Count == 0;

    /// <summary>Determines if this provider can handle the given search result.</summary>
    bool CanProvide(ISearchResult result);

    /// <summary>
    /// Populates and returns menu items for the root menu (hMenu = Zero) or a sub-menu.
    /// </summary>
    IEnumerable<DynamicMenuItem> GetMenuItems(ISearchResult result, IntPtr hMenu);

    /// <summary>Invokes a dynamic command by its ID.</summary>
    void ExecuteCommand(ISearchResult result, uint commandId, IntPtr ownerHwnd);

    /// <summary>Cleans up any allocated session resources (e.g., when exiting the action list).</summary>
    void ClearSession();
}

/// <summary>
/// Represents an individual menu item generated by a dynamic provider.
/// </summary>
public class DynamicMenuItem
{
    public string Text { get; set; } = string.Empty;
    public uint CommandId { get; set; }
    public bool IsSeparator { get; set; }
    public bool HasSubMenu { get; set; }
    public IntPtr SubMenuHandle { get; set; }
    public bool IsDisabled { get; set; }
    public IntPtr HBitmapItem { get; set; }
    /// <summary>
    /// Optional direct invocation delegate set by the plugin.
    /// When non-null, the host calls this instead of routing through
    /// <see cref="IQuickNavigationProvider.ExecuteCommand"/> or path navigation.
    /// Plugins use this for items whose execution logic they own entirely
    /// (e.g. virtual Shell namespace items, custom actions).
    /// </summary>
    public Action? OnExecute { get; set; }
}
